Search.appendIndex(
    [
                {
            "fqsen": "\\Core\\Interfaces\\LoggerFactory",
            "name": "LoggerFactory",
            "summary": "",
            "url": "classes/Core-Interfaces-LoggerFactory.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\LoggerFactory\u003A\u003AlogFile\u0028\u0029",
            "name": "logFile",
            "summary": "Simple\u0020log\u0020to\u0020some\u0020file\nThe\u0020file\u0020will\u0020created\u0020if\u0020not\u0020exists",
            "url": "classes/Core-Interfaces-LoggerFactory.html#method_logFile"
        },                {
            "fqsen": "\\Core\\Interfaces\\LoggerFactory\u003A\u003AlogStd\u0028\u0029",
            "name": "logStd",
            "summary": "Simple\u0020log\u0020to\u0020std\nInfo\u0020will\u0020go\u0020to\u0020stdout,\u0020errors\u0020go\u0020to\u0020stderr",
            "url": "classes/Core-Interfaces-LoggerFactory.html#method_logStd"
        },                {
            "fqsen": "\\Core\\Interfaces\\LoggerFactory\u003A\u003AlogNull\u0028\u0029",
            "name": "logNull",
            "summary": "Log\u0020adapter\u0020stub.\u0020Do\u0020not\u0020make\u0020anything\u003B",
            "url": "classes/Core-Interfaces-LoggerFactory.html#method_logNull"
        },                {
            "fqsen": "\\Core\\Interfaces\\LoggerFactory\u003A\u003AgetLogger\u0028\u0029",
            "name": "getLogger",
            "summary": "Get\u0020logger\u0020without\u0020imported\u0020adapter\nYou\u0020can\u0020make\u0020plug\u0020own\u0020that\u0020extends\u0020of\u0020LoggerRoute",
            "url": "classes/Core-Interfaces-LoggerFactory.html#method_getLogger"
        },                {
            "fqsen": "\\Core\\Interfaces\\SimpleLogger",
            "name": "SimpleLogger",
            "summary": "",
            "url": "classes/Core-Interfaces-SimpleLogger.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\SimpleLogger\u003A\u003AaddBroadcast\u0028\u0029",
            "name": "addBroadcast",
            "summary": "Add\u0020destination\u0020to\u0020broadcast\u0020log",
            "url": "classes/Core-Interfaces-SimpleLogger.html#method_addBroadcast"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteFile",
            "name": "LoggerRouteFile",
            "summary": "File\u0020logger",
            "url": "classes/Core-Logger-Adapters-LoggerRouteFile.html"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteFile\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Logger-Adapters-LoggerRouteFile.html#method___construct"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteFile\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "Log\u0020to\u0020file",
            "url": "classes/Core-Logger-Adapters-LoggerRouteFile.html#method_log"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteFile\u003A\u003AsetFilePath\u0028\u0029",
            "name": "setFilePath",
            "summary": "Set\u0020file\u0020path\u0020for\u0020log\u0020file",
            "url": "classes/Core-Logger-Adapters-LoggerRouteFile.html#method_setFilePath"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteFile\u003A\u003AsetTemplate\u0028\u0029",
            "name": "setTemplate",
            "summary": "Set\u0020template.",
            "url": "classes/Core-Logger-Adapters-LoggerRouteFile.html#method_setTemplate"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteFile\u003A\u003A\u0024isEnable",
            "name": "isEnable",
            "summary": "If\u0020this\u0020logger\u0020route\u0020enable",
            "url": "classes/Core-Logger-Adapters-LoggerRouteFile.html#property_isEnable"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteFile\u003A\u003A\u0024filePath",
            "name": "filePath",
            "summary": "Path\u0020to\u0020file\u0020log",
            "url": "classes/Core-Logger-Adapters-LoggerRouteFile.html#property_filePath"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteFile\u003A\u003A\u0024template",
            "name": "template",
            "summary": "Log\u0020record\u0020template",
            "url": "classes/Core-Logger-Adapters-LoggerRouteFile.html#property_template"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteNull",
            "name": "LoggerRouteNull",
            "summary": "Null\u0020logger",
            "url": "classes/Core-Logger-Adapters-LoggerRouteNull.html"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteNull\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Logger-Adapters-LoggerRouteNull.html#method___construct"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteNull\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "Log\u0020to\u0020null",
            "url": "classes/Core-Logger-Adapters-LoggerRouteNull.html#method_log"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteNull\u003A\u003A\u0024isEnable",
            "name": "isEnable",
            "summary": "If\u0020this\u0020log\u0020route\u0020enabled",
            "url": "classes/Core-Logger-Adapters-LoggerRouteNull.html#property_isEnable"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteStd",
            "name": "LoggerRouteStd",
            "summary": "Logger\u0020for\u0020STDerr\u0020or\u0020STDout.\u0020For\u0020example\u0020it\u0020usable\u0020in\u0020docker",
            "url": "classes/Core-Logger-Adapters-LoggerRouteStd.html"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteStd\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "",
            "url": "classes/Core-Logger-Adapters-LoggerRouteStd.html#method_log"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteStd\u003A\u003AsetTemplate\u0028\u0029",
            "name": "setTemplate",
            "summary": "Set\u0020log\u0020entry\u0020template",
            "url": "classes/Core-Logger-Adapters-LoggerRouteStd.html#method_setTemplate"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteStd\u003A\u003AisErrorLevel\u0028\u0029",
            "name": "isErrorLevel",
            "summary": "Whitch\u0020of\u0020these\u0020levels\u0020is\u0020errors.\u0020Other\u0020will\u0020go\u0020to\u0020stdout",
            "url": "classes/Core-Logger-Adapters-LoggerRouteStd.html#method_isErrorLevel"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteStd\u003A\u003A\u0024echo",
            "name": "echo",
            "summary": "For\u0020tests\u0020\u002D\u0020echo\u0020result",
            "url": "classes/Core-Logger-Adapters-LoggerRouteStd.html#property_echo"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteStd\u003A\u003A\u0024isEnable",
            "name": "isEnable",
            "summary": "if\u0020this\u0020logger\u0020route\u0020enabled",
            "url": "classes/Core-Logger-Adapters-LoggerRouteStd.html#property_isEnable"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters\\LoggerRouteStd\u003A\u003A\u0024template",
            "name": "template",
            "summary": "Log\u0020entry\u0020template",
            "url": "classes/Core-Logger-Adapters-LoggerRouteStd.html#property_template"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerFactoryGeneric",
            "name": "LoggerFactoryGeneric",
            "summary": "",
            "url": "classes/Core-Logger-LoggerFactoryGeneric.html"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerFactoryGeneric\u003A\u003AlogFile\u0028\u0029",
            "name": "logFile",
            "summary": "log\u0020to\u0020file",
            "url": "classes/Core-Logger-LoggerFactoryGeneric.html#method_logFile"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerFactoryGeneric\u003A\u003AlogStd\u0028\u0029",
            "name": "logStd",
            "summary": "log\u0020to\u0020STD",
            "url": "classes/Core-Logger-LoggerFactoryGeneric.html#method_logStd"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerFactoryGeneric\u003A\u003AlogNull\u0028\u0029",
            "name": "logNull",
            "summary": "Log\u0020to\u0020null",
            "url": "classes/Core-Logger-LoggerFactoryGeneric.html#method_logNull"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerFactoryGeneric\u003A\u003AgetLogger\u0028\u0029",
            "name": "getLogger",
            "summary": "Get\u0020logger\u0020without\u0020imported\u0020adapter\nYou\u0020can\u0020make\u0020plug\u0020own\u0020that\u0020extends\u0020of\u0020LoggerRoute",
            "url": "classes/Core-Logger-LoggerFactoryGeneric.html#method_getLogger"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerGeneric",
            "name": "LoggerGeneric",
            "summary": "",
            "url": "classes/Core-Logger-LoggerGeneric.html"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerGeneric\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "Log\u0020the\u0020message",
            "url": "classes/Core-Logger-LoggerGeneric.html#method_log"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerGeneric\u003A\u003AaddBroadcast\u0028\u0029",
            "name": "addBroadcast",
            "summary": "Add\u0020broadcast\u0020item\u0020to\u0020logging",
            "url": "classes/Core-Logger-LoggerGeneric.html#method_addBroadcast"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerGeneric\u003A\u003A\u0024broadcast",
            "name": "broadcast",
            "summary": "Array\u0020of\u0020logger\u0020routes\u0020for\u0020broadcast",
            "url": "classes/Core-Logger-LoggerGeneric.html#property_broadcast"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerRoute",
            "name": "LoggerRoute",
            "summary": "Abstract\u0020logger\u0020route,\u0020the\u0020father\u0020of\u0020all\u0020routes",
            "url": "classes/Core-Logger-LoggerRoute.html"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerRoute\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Logger-LoggerRoute.html#method___construct"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerRoute\u003A\u003AgetDate\u0028\u0029",
            "name": "getDate",
            "summary": "Current\u0020date",
            "url": "classes/Core-Logger-LoggerRoute.html#method_getDate"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerRoute\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "Convert\u0020\u0024context\u0020to\u0020string",
            "url": "classes/Core-Logger-LoggerRoute.html#method_toString"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerRoute\u003A\u003A\u0024isEnable",
            "name": "isEnable",
            "summary": "If\u0020route\u0020enable",
            "url": "classes/Core-Logger-LoggerRoute.html#property_isEnable"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerRoute\u003A\u003AsetIsEnable\u0028\u0029",
            "name": "setIsEnable",
            "summary": "Turn\u0020on\u0020or\u0020off\u0020this\u0020route",
            "url": "classes/Core-Logger-LoggerRoute.html#method_setIsEnable"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerRoute\u003A\u003AsetDateFormat\u0028\u0029",
            "name": "setDateFormat",
            "summary": "Set\u0020default\u0020date\u0020format",
            "url": "classes/Core-Logger-LoggerRoute.html#method_setDateFormat"
        },                {
            "fqsen": "\\Core\\Logger\\LoggerRoute\u003A\u003A\u0024dateFormat",
            "name": "dateFormat",
            "summary": "Date\u0020format",
            "url": "classes/Core-Logger-LoggerRoute.html#property_dateFormat"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Core\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/core-interfaces.html"
        },                {
            "fqsen": "\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/core.html"
        },                {
            "fqsen": "\\Core\\Logger\\Adapters",
            "name": "Adapters",
            "summary": "",
            "url": "namespaces/core-logger-adapters.html"
        },                {
            "fqsen": "\\Core\\Logger",
            "name": "Logger",
            "summary": "",
            "url": "namespaces/core-logger.html"
        }            ]
);
